# 워크플로우 -> 자동화 할 작업의 설계서 -> action.yml
#

name: first workflow
on: push # 이벤트 트리거
jobs:
  build:
    runs-on: ubuntu-latest
    steps: # step 정의
      #레포지토리 -> 가상 환경으로 코드 가져오기
      - name: Checkout Code
        uses: actions/checkout@v4 # actions -> 재사용 가능한 작업

        #노드 버전을 맞춰야 할 경우 가상환경에 노드를 추가 설치
      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: install deps
        run: npm ci # clean install -> package-lock.json

      - name: run build
        run: npm run build

  # npm run lint
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout node
        uses: actions/checkout@v4

      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: install dependencies
        run: npm ci

      - name: run lint
        run: npm run lint
